# coding: utf-8

# flake8: noqa
"""
    Bazarr

    API docs for Bazarr

    The version of the OpenAPI document: 1.5.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from bazarr.models.general_settings import GeneralSettings
from bazarr.models.radarr_movie import RadarrMovie
from bazarr.models.radarr_movie_file import RadarrMovieFile
from bazarr.models.radarr_settings import RadarrSettings
from bazarr.models.radarr_webhook import RadarrWebhook
from bazarr.models.sonarr_episode import SonarrEpisode
from bazarr.models.sonarr_episode_file import SonarrEpisodeFile
from bazarr.models.sonarr_settings import SonarrSettings
from bazarr.models.sonarr_webhook import SonarrWebhook
from bazarr.models.system_settings import SystemSettings
from bazarr.models.system_settings_update import SystemSettingsUpdate

