# coding: utf-8

"""
    Bazarr

    API docs for Bazarr

    The version of the OpenAPI document: 1.5.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class GeneralSettings(BaseModel):
    """
    General Bazarr settings
    """ # noqa: E501
    enabled_providers: Optional[List[StrictStr]] = Field(default=None, description="List of enabled subtitle providers")
    minimum_score: Optional[StrictInt] = Field(default=None, description="Minimum score for series subtitles")
    minimum_score_movie: Optional[StrictInt] = Field(default=None, description="Minimum score for movie subtitles")
    use_sonarr: Optional[StrictBool] = Field(default=None, description="Enable Sonarr integration")
    use_radarr: Optional[StrictBool] = Field(default=None, description="Enable Radarr integration")
    upgrade_subs: Optional[StrictBool] = Field(default=None, description="Enable subtitle upgrades")
    days_to_upgrade_subs: Optional[StrictInt] = Field(default=None, description="Days to keep searching for upgraded subtitles")
    wanted_search_frequency: Optional[StrictInt] = Field(default=None, description="Series wanted search frequency in hours")
    wanted_search_frequency_movie: Optional[StrictInt] = Field(default=None, description="Movie wanted search frequency in hours")
    use_embedded_subs: Optional[StrictBool] = Field(default=None, description="Use embedded subtitles")
    adaptive_searching: Optional[StrictBool] = Field(default=None, description="Enable adaptive searching")
    single_language: Optional[StrictBool] = Field(default=None, description="Single language mode")
    serie_default_profile: Optional[StrictInt] = Field(default=None, description="Default language profile ID for series")
    movie_default_profile: Optional[StrictInt] = Field(default=None, description="Default language profile ID for movies")
    __properties: ClassVar[List[str]] = ["enabled_providers", "minimum_score", "minimum_score_movie", "use_sonarr", "use_radarr", "upgrade_subs", "days_to_upgrade_subs", "wanted_search_frequency", "wanted_search_frequency_movie", "use_embedded_subs", "adaptive_searching", "single_language", "serie_default_profile", "movie_default_profile"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GeneralSettings from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GeneralSettings from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "enabled_providers": obj.get("enabled_providers"),
            "minimum_score": obj.get("minimum_score"),
            "minimum_score_movie": obj.get("minimum_score_movie"),
            "use_sonarr": obj.get("use_sonarr"),
            "use_radarr": obj.get("use_radarr"),
            "upgrade_subs": obj.get("upgrade_subs"),
            "days_to_upgrade_subs": obj.get("days_to_upgrade_subs"),
            "wanted_search_frequency": obj.get("wanted_search_frequency"),
            "wanted_search_frequency_movie": obj.get("wanted_search_frequency_movie"),
            "use_embedded_subs": obj.get("use_embedded_subs"),
            "adaptive_searching": obj.get("adaptive_searching"),
            "single_language": obj.get("single_language"),
            "serie_default_profile": obj.get("serie_default_profile"),
            "movie_default_profile": obj.get("movie_default_profile")
        })
        return _obj


