# coding: utf-8

"""
    Bazarr

    API docs for Bazarr

    The version of the OpenAPI document: 1.5.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from bazarr.models.radarr_movie import RadarrMovie
from bazarr.models.radarr_movie_file import RadarrMovieFile
from typing import Optional, Set
from typing_extensions import Self

class RadarrWebhook(BaseModel):
    """
    RadarrWebhook
    """ # noqa: E501
    event_type: StrictStr = Field(description="Type of Radarr event (e.g. MovieAdded, Test, etc)", alias="eventType")
    movie_file: Optional[RadarrMovieFile] = Field(default=None, description="Radarr movie file payload. Required for anything other than test hooks", alias="movieFile")
    movie: Optional[RadarrMovie] = Field(default=None, description="Radarr movie payload. Can be used to sync movies from Radarr if not found in Bazarr")
    __properties: ClassVar[List[str]] = ["eventType", "movieFile", "movie"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RadarrWebhook from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of movie_file
        if self.movie_file:
            _dict['movieFile'] = self.movie_file.to_dict()
        # override the default output from pydantic by calling `to_dict()` of movie
        if self.movie:
            _dict['movie'] = self.movie.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RadarrWebhook from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "eventType": obj.get("eventType"),
            "movieFile": RadarrMovieFile.from_dict(obj["movieFile"]) if obj.get("movieFile") is not None else None,
            "movie": RadarrMovie.from_dict(obj["movie"]) if obj.get("movie") is not None else None
        })
        return _obj


