# coding: utf-8

"""
    Bazarr

    API docs for Bazarr

    The version of the OpenAPI document: 1.5.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class RadarrSettings(BaseModel):
    """
    Radarr connection settings
    """ # noqa: E501
    ip: Optional[StrictStr] = Field(default=None, description="Radarr IP address or hostname")
    port: Optional[StrictInt] = Field(default=None, description="Radarr port")
    base_url: Optional[StrictStr] = Field(default=None, description="Radarr base URL path")
    ssl: Optional[StrictBool] = Field(default=None, description="Use SSL/HTTPS")
    apikey: Optional[StrictStr] = Field(default=None, description="Radarr API key")
    full_update: Optional[StrictStr] = Field(default=None, description="Full update frequency")
    full_update_day: Optional[StrictInt] = Field(default=None, description="Day for full update")
    full_update_hour: Optional[StrictInt] = Field(default=None, description="Hour for full update")
    only_monitored: Optional[StrictBool] = Field(default=None, description="Only sync monitored movies")
    movies_sync: Optional[StrictInt] = Field(default=None, description="Movies sync interval in minutes")
    excluded_tags: Optional[List[StrictStr]] = Field(default=None, description="Tags to exclude from sync")
    __properties: ClassVar[List[str]] = ["ip", "port", "base_url", "ssl", "apikey", "full_update", "full_update_day", "full_update_hour", "only_monitored", "movies_sync", "excluded_tags"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RadarrSettings from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RadarrSettings from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "ip": obj.get("ip"),
            "port": obj.get("port"),
            "base_url": obj.get("base_url"),
            "ssl": obj.get("ssl"),
            "apikey": obj.get("apikey"),
            "full_update": obj.get("full_update"),
            "full_update_day": obj.get("full_update_day"),
            "full_update_hour": obj.get("full_update_hour"),
            "only_monitored": obj.get("only_monitored"),
            "movies_sync": obj.get("movies_sync"),
            "excluded_tags": obj.get("excluded_tags")
        })
        return _obj


