# coding: utf-8

"""
    Bazarr

    API docs for Bazarr

    The version of the OpenAPI document: 1.5.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from bazarr.models.sonarr_episode import SonarrEpisode
from bazarr.models.sonarr_episode_file import SonarrEpisodeFile
from typing import Optional, Set
from typing_extensions import Self

class SonarrWebhook(BaseModel):
    """
    SonarrWebhook
    """ # noqa: E501
    episodes: Optional[List[SonarrEpisode]] = Field(default=None, description="List of episodes. Can be used to sync episodes from Sonarr if not found in Bazarr.")
    episode_files: Optional[List[SonarrEpisodeFile]] = Field(default=None, description="List of episode files; required for anything other than test hooks", alias="episodeFiles")
    event_type: StrictStr = Field(description="Type of Sonarr event (e.g. Test, Download, etc.)", alias="eventType")
    __properties: ClassVar[List[str]] = ["episodes", "episodeFiles", "eventType"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SonarrWebhook from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in episodes (list)
        _items = []
        if self.episodes:
            for _item_episodes in self.episodes:
                if _item_episodes:
                    _items.append(_item_episodes.to_dict())
            _dict['episodes'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in episode_files (list)
        _items = []
        if self.episode_files:
            for _item_episode_files in self.episode_files:
                if _item_episode_files:
                    _items.append(_item_episode_files.to_dict())
            _dict['episodeFiles'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SonarrWebhook from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "episodes": [SonarrEpisode.from_dict(_item) for _item in obj["episodes"]] if obj.get("episodes") is not None else None,
            "episodeFiles": [SonarrEpisodeFile.from_dict(_item) for _item in obj["episodeFiles"]] if obj.get("episodeFiles") is not None else None,
            "eventType": obj.get("eventType")
        })
        return _obj


