# coding: utf-8

"""
    Bazarr

    API docs for Bazarr

    The version of the OpenAPI document: 1.5.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from bazarr.models.general_settings import GeneralSettings
from bazarr.models.radarr_settings import RadarrSettings
from bazarr.models.sonarr_settings import SonarrSettings
from typing import Optional, Set
from typing_extensions import Self

class SystemSettings(BaseModel):
    """
    All Bazarr system settings
    """ # noqa: E501
    general: Optional[GeneralSettings] = None
    sonarr: Optional[SonarrSettings] = None
    radarr: Optional[RadarrSettings] = None
    analytics: Optional[Dict[str, Any]] = Field(default=None, description="Analytics settings")
    auth: Optional[Dict[str, Any]] = Field(default=None, description="Authentication settings")
    backup: Optional[Dict[str, Any]] = Field(default=None, description="Backup settings")
    betamap: Optional[Dict[str, Any]] = Field(default=None, description="Beta mapping settings")
    cors: Optional[Dict[str, Any]] = Field(default=None, description="CORS settings")
    opensubtitles: Optional[Dict[str, Any]] = Field(default=None, description="OpenSubtitles provider settings")
    opensubtitlescom: Optional[Dict[str, Any]] = Field(default=None, description="OpenSubtitles.com provider settings")
    postgresql: Optional[Dict[str, Any]] = Field(default=None, description="PostgreSQL settings")
    proxy: Optional[Dict[str, Any]] = Field(default=None, description="Proxy settings")
    scheduler: Optional[Dict[str, Any]] = Field(default=None, description="Scheduler settings")
    sonarr_sync: Optional[Dict[str, Any]] = Field(default=None, description="Sonarr sync settings")
    radarr_sync: Optional[Dict[str, Any]] = Field(default=None, description="Radarr sync settings")
    subsync: Optional[Dict[str, Any]] = Field(default=None, description="Subtitle sync settings")
    subtitlesearching: Optional[Dict[str, Any]] = Field(default=None, description="Subtitle searching settings")
    titulky: Optional[Dict[str, Any]] = Field(default=None, description="Titulky provider settings")
    anidb: Optional[Dict[str, Any]] = Field(default=None, description="AniDB settings")
    gestdown: Optional[Dict[str, Any]] = Field(default=None, description="Gestdown provider settings")
    whisperai: Optional[Dict[str, Any]] = Field(default=None, description="Whisper AI settings")
    __properties: ClassVar[List[str]] = ["general", "sonarr", "radarr", "analytics", "auth", "backup", "betamap", "cors", "opensubtitles", "opensubtitlescom", "postgresql", "proxy", "scheduler", "sonarr_sync", "radarr_sync", "subsync", "subtitlesearching", "titulky", "anidb", "gestdown", "whisperai"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SystemSettings from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of general
        if self.general:
            _dict['general'] = self.general.to_dict()
        # override the default output from pydantic by calling `to_dict()` of sonarr
        if self.sonarr:
            _dict['sonarr'] = self.sonarr.to_dict()
        # override the default output from pydantic by calling `to_dict()` of radarr
        if self.radarr:
            _dict['radarr'] = self.radarr.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SystemSettings from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "general": GeneralSettings.from_dict(obj["general"]) if obj.get("general") is not None else None,
            "sonarr": SonarrSettings.from_dict(obj["sonarr"]) if obj.get("sonarr") is not None else None,
            "radarr": RadarrSettings.from_dict(obj["radarr"]) if obj.get("radarr") is not None else None,
            "analytics": obj.get("analytics"),
            "auth": obj.get("auth"),
            "backup": obj.get("backup"),
            "betamap": obj.get("betamap"),
            "cors": obj.get("cors"),
            "opensubtitles": obj.get("opensubtitles"),
            "opensubtitlescom": obj.get("opensubtitlescom"),
            "postgresql": obj.get("postgresql"),
            "proxy": obj.get("proxy"),
            "scheduler": obj.get("scheduler"),
            "sonarr_sync": obj.get("sonarr_sync"),
            "radarr_sync": obj.get("radarr_sync"),
            "subsync": obj.get("subsync"),
            "subtitlesearching": obj.get("subtitlesearching"),
            "titulky": obj.get("titulky"),
            "anidb": obj.get("anidb"),
            "gestdown": obj.get("gestdown"),
            "whisperai": obj.get("whisperai")
        })
        return _obj


