# coding: utf-8

# flake8: noqa

"""
    Bazarr

    API docs for Bazarr

    The version of the OpenAPI document: 1.5.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "BadgesApi",
    "EpisodesApi",
    "EpisodesBlacklistApi",
    "EpisodesHistoryApi",
    "EpisodesSubtitlesApi",
    "EpisodesWantedApi",
    "FilesBrowserForBazarrApi",
    "FilesBrowserForRadarrApi",
    "FilesBrowserForSonarrApi",
    "HistoryStatisticsApi",
    "MoviesApi",
    "MoviesBlacklistApi",
    "MoviesHistoryApi",
    "MoviesSubtitlesApi",
    "MoviesWantedApi",
    "PlexAuthenticationApi",
    "ProvidersApi",
    "ProvidersEpisodesApi",
    "ProvidersMoviesApi",
    "SeriesApi",
    "SubtitlesApi",
    "SubtitlesInfoApi",
    "SystemAnnouncementsApi",
    "SystemBackupsApi",
    "SystemHealthApi",
    "SystemJobsApi",
    "SystemLanguagesApi",
    "SystemLanguagesProfilesApi",
    "SystemLogsApi",
    "SystemPingApi",
    "SystemReleasesApi",
    "SystemSearchesApi",
    "SystemSettingsApi",
    "SystemStatusApi",
    "SystemTasksApi",
    "WebhooksPlexApi",
    "WebhooksRadarrApi",
    "WebhooksSonarrApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "GeneralSettings",
    "RadarrMovie",
    "RadarrMovieFile",
    "RadarrSettings",
    "RadarrWebhook",
    "SonarrEpisode",
    "SonarrEpisodeFile",
    "SonarrSettings",
    "SonarrWebhook",
    "SystemSettings",
    "SystemSettingsUpdate",
]

# import apis into sdk package
from bazarr.api.badges_api import BadgesApi as BadgesApi
from bazarr.api.episodes_api import EpisodesApi as EpisodesApi
from bazarr.api.episodes_blacklist_api import EpisodesBlacklistApi as EpisodesBlacklistApi
from bazarr.api.episodes_history_api import EpisodesHistoryApi as EpisodesHistoryApi
from bazarr.api.episodes_subtitles_api import EpisodesSubtitlesApi as EpisodesSubtitlesApi
from bazarr.api.episodes_wanted_api import EpisodesWantedApi as EpisodesWantedApi
from bazarr.api.files_browser_for_bazarr_api import FilesBrowserForBazarrApi as FilesBrowserForBazarrApi
from bazarr.api.files_browser_for_radarr_api import FilesBrowserForRadarrApi as FilesBrowserForRadarrApi
from bazarr.api.files_browser_for_sonarr_api import FilesBrowserForSonarrApi as FilesBrowserForSonarrApi
from bazarr.api.history_statistics_api import HistoryStatisticsApi as HistoryStatisticsApi
from bazarr.api.movies_api import MoviesApi as MoviesApi
from bazarr.api.movies_blacklist_api import MoviesBlacklistApi as MoviesBlacklistApi
from bazarr.api.movies_history_api import MoviesHistoryApi as MoviesHistoryApi
from bazarr.api.movies_subtitles_api import MoviesSubtitlesApi as MoviesSubtitlesApi
from bazarr.api.movies_wanted_api import MoviesWantedApi as MoviesWantedApi
from bazarr.api.plex_authentication_api import PlexAuthenticationApi as PlexAuthenticationApi
from bazarr.api.providers_api import ProvidersApi as ProvidersApi
from bazarr.api.providers_episodes_api import ProvidersEpisodesApi as ProvidersEpisodesApi
from bazarr.api.providers_movies_api import ProvidersMoviesApi as ProvidersMoviesApi
from bazarr.api.series_api import SeriesApi as SeriesApi
from bazarr.api.subtitles_api import SubtitlesApi as SubtitlesApi
from bazarr.api.subtitles_info_api import SubtitlesInfoApi as SubtitlesInfoApi
from bazarr.api.system_announcements_api import SystemAnnouncementsApi as SystemAnnouncementsApi
from bazarr.api.system_backups_api import SystemBackupsApi as SystemBackupsApi
from bazarr.api.system_health_api import SystemHealthApi as SystemHealthApi
from bazarr.api.system_jobs_api import SystemJobsApi as SystemJobsApi
from bazarr.api.system_languages_api import SystemLanguagesApi as SystemLanguagesApi
from bazarr.api.system_languages_profiles_api import SystemLanguagesProfilesApi as SystemLanguagesProfilesApi
from bazarr.api.system_logs_api import SystemLogsApi as SystemLogsApi
from bazarr.api.system_ping_api import SystemPingApi as SystemPingApi
from bazarr.api.system_releases_api import SystemReleasesApi as SystemReleasesApi
from bazarr.api.system_searches_api import SystemSearchesApi as SystemSearchesApi
from bazarr.api.system_settings_api import SystemSettingsApi as SystemSettingsApi
from bazarr.api.system_status_api import SystemStatusApi as SystemStatusApi
from bazarr.api.system_tasks_api import SystemTasksApi as SystemTasksApi
from bazarr.api.webhooks_plex_api import WebhooksPlexApi as WebhooksPlexApi
from bazarr.api.webhooks_radarr_api import WebhooksRadarrApi as WebhooksRadarrApi
from bazarr.api.webhooks_sonarr_api import WebhooksSonarrApi as WebhooksSonarrApi

# import ApiClient
from bazarr.api_response import ApiResponse as ApiResponse
from bazarr.api_client import ApiClient as ApiClient
from bazarr.configuration import Configuration as Configuration
from bazarr.exceptions import OpenApiException as OpenApiException
from bazarr.exceptions import ApiTypeError as ApiTypeError
from bazarr.exceptions import ApiValueError as ApiValueError
from bazarr.exceptions import ApiKeyError as ApiKeyError
from bazarr.exceptions import ApiAttributeError as ApiAttributeError
from bazarr.exceptions import ApiException as ApiException

# import models into sdk package
from bazarr.models.general_settings import GeneralSettings as GeneralSettings
from bazarr.models.radarr_movie import RadarrMovie as RadarrMovie
from bazarr.models.radarr_movie_file import RadarrMovieFile as RadarrMovieFile
from bazarr.models.radarr_settings import RadarrSettings as RadarrSettings
from bazarr.models.radarr_webhook import RadarrWebhook as RadarrWebhook
from bazarr.models.sonarr_episode import SonarrEpisode as SonarrEpisode
from bazarr.models.sonarr_episode_file import SonarrEpisodeFile as SonarrEpisodeFile
from bazarr.models.sonarr_settings import SonarrSettings as SonarrSettings
from bazarr.models.sonarr_webhook import SonarrWebhook as SonarrWebhook
from bazarr.models.system_settings import SystemSettings as SystemSettings
from bazarr.models.system_settings_update import SystemSettingsUpdate as SystemSettingsUpdate

