# coding: utf-8

"""
    Bazarr

    API docs for Bazarr

    The version of the OpenAPI document: 1.5.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictBytes, StrictInt, StrictStr
from typing import Tuple, Union
from typing_extensions import Annotated

from bazarr.api_client import ApiClient, RequestSerialized
from bazarr.api_response import ApiResponse
from bazarr.rest import RESTResponseType


class EpisodesSubtitlesApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def delete_episodes_subtitles(
        self,
        seriesid: Annotated[StrictInt, Field(description="Series ID")],
        episodeid: Annotated[StrictInt, Field(description="Episode ID")],
        language: Annotated[StrictStr, Field(description="Language code2")],
        forced: Annotated[StrictStr, Field(description="Forced true/false as string")],
        hi: Annotated[StrictStr, Field(description="HI true/false as string")],
        path: Annotated[StrictStr, Field(description="Path of the subtitles file")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> None:
        """Delete an episode subtitles


        :param seriesid: Series ID (required)
        :type seriesid: int
        :param episodeid: Episode ID (required)
        :type episodeid: int
        :param language: Language code2 (required)
        :type language: str
        :param forced: Forced true/false as string (required)
        :type forced: str
        :param hi: HI true/false as string (required)
        :type hi: str
        :param path: Path of the subtitles file (required)
        :type path: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._delete_episodes_subtitles_serialize(
            seriesid=seriesid,
            episodeid=episodeid,
            language=language,
            forced=forced,
            hi=hi,
            path=path,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '500': None,
            '404': None,
            '401': None,
            '204': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def delete_episodes_subtitles_with_http_info(
        self,
        seriesid: Annotated[StrictInt, Field(description="Series ID")],
        episodeid: Annotated[StrictInt, Field(description="Episode ID")],
        language: Annotated[StrictStr, Field(description="Language code2")],
        forced: Annotated[StrictStr, Field(description="Forced true/false as string")],
        hi: Annotated[StrictStr, Field(description="HI true/false as string")],
        path: Annotated[StrictStr, Field(description="Path of the subtitles file")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[None]:
        """Delete an episode subtitles


        :param seriesid: Series ID (required)
        :type seriesid: int
        :param episodeid: Episode ID (required)
        :type episodeid: int
        :param language: Language code2 (required)
        :type language: str
        :param forced: Forced true/false as string (required)
        :type forced: str
        :param hi: HI true/false as string (required)
        :type hi: str
        :param path: Path of the subtitles file (required)
        :type path: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._delete_episodes_subtitles_serialize(
            seriesid=seriesid,
            episodeid=episodeid,
            language=language,
            forced=forced,
            hi=hi,
            path=path,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '500': None,
            '404': None,
            '401': None,
            '204': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def delete_episodes_subtitles_without_preload_content(
        self,
        seriesid: Annotated[StrictInt, Field(description="Series ID")],
        episodeid: Annotated[StrictInt, Field(description="Episode ID")],
        language: Annotated[StrictStr, Field(description="Language code2")],
        forced: Annotated[StrictStr, Field(description="Forced true/false as string")],
        hi: Annotated[StrictStr, Field(description="HI true/false as string")],
        path: Annotated[StrictStr, Field(description="Path of the subtitles file")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Delete an episode subtitles


        :param seriesid: Series ID (required)
        :type seriesid: int
        :param episodeid: Episode ID (required)
        :type episodeid: int
        :param language: Language code2 (required)
        :type language: str
        :param forced: Forced true/false as string (required)
        :type forced: str
        :param hi: HI true/false as string (required)
        :type hi: str
        :param path: Path of the subtitles file (required)
        :type path: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._delete_episodes_subtitles_serialize(
            seriesid=seriesid,
            episodeid=episodeid,
            language=language,
            forced=forced,
            hi=hi,
            path=path,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '500': None,
            '404': None,
            '401': None,
            '204': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _delete_episodes_subtitles_serialize(
        self,
        seriesid,
        episodeid,
        language,
        forced,
        hi,
        path,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if seriesid is not None:
            
            _query_params.append(('seriesid', seriesid))
            
        if episodeid is not None:
            
            _query_params.append(('episodeid', episodeid))
            
        if language is not None:
            
            _query_params.append(('language', language))
            
        if forced is not None:
            
            _query_params.append(('forced', forced))
            
        if hi is not None:
            
            _query_params.append(('hi', hi))
            
        if path is not None:
            
            _query_params.append(('path', path))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter




        # authentication setting
        _auth_settings: List[str] = [
            'apikey'
        ]

        return self.api_client.param_serialize(
            method='DELETE',
            resource_path='/episodes/subtitles',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def patch_episodes_subtitles(
        self,
        seriesid: Annotated[StrictInt, Field(description="Series ID")],
        episodeid: Annotated[StrictInt, Field(description="Episode ID")],
        language: Annotated[StrictStr, Field(description="Language code2")],
        forced: Annotated[StrictStr, Field(description="Forced true/false as string")],
        hi: Annotated[StrictStr, Field(description="HI true/false as string")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> None:
        """Download an episode subtitles


        :param seriesid: Series ID (required)
        :type seriesid: int
        :param episodeid: Episode ID (required)
        :type episodeid: int
        :param language: Language code2 (required)
        :type language: str
        :param forced: Forced true/false as string (required)
        :type forced: str
        :param hi: HI true/false as string (required)
        :type hi: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._patch_episodes_subtitles_serialize(
            seriesid=seriesid,
            episodeid=episodeid,
            language=language,
            forced=forced,
            hi=hi,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '500': None,
            '409': None,
            '404': None,
            '401': None,
            '204': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def patch_episodes_subtitles_with_http_info(
        self,
        seriesid: Annotated[StrictInt, Field(description="Series ID")],
        episodeid: Annotated[StrictInt, Field(description="Episode ID")],
        language: Annotated[StrictStr, Field(description="Language code2")],
        forced: Annotated[StrictStr, Field(description="Forced true/false as string")],
        hi: Annotated[StrictStr, Field(description="HI true/false as string")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[None]:
        """Download an episode subtitles


        :param seriesid: Series ID (required)
        :type seriesid: int
        :param episodeid: Episode ID (required)
        :type episodeid: int
        :param language: Language code2 (required)
        :type language: str
        :param forced: Forced true/false as string (required)
        :type forced: str
        :param hi: HI true/false as string (required)
        :type hi: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._patch_episodes_subtitles_serialize(
            seriesid=seriesid,
            episodeid=episodeid,
            language=language,
            forced=forced,
            hi=hi,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '500': None,
            '409': None,
            '404': None,
            '401': None,
            '204': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def patch_episodes_subtitles_without_preload_content(
        self,
        seriesid: Annotated[StrictInt, Field(description="Series ID")],
        episodeid: Annotated[StrictInt, Field(description="Episode ID")],
        language: Annotated[StrictStr, Field(description="Language code2")],
        forced: Annotated[StrictStr, Field(description="Forced true/false as string")],
        hi: Annotated[StrictStr, Field(description="HI true/false as string")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Download an episode subtitles


        :param seriesid: Series ID (required)
        :type seriesid: int
        :param episodeid: Episode ID (required)
        :type episodeid: int
        :param language: Language code2 (required)
        :type language: str
        :param forced: Forced true/false as string (required)
        :type forced: str
        :param hi: HI true/false as string (required)
        :type hi: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._patch_episodes_subtitles_serialize(
            seriesid=seriesid,
            episodeid=episodeid,
            language=language,
            forced=forced,
            hi=hi,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '500': None,
            '409': None,
            '404': None,
            '401': None,
            '204': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _patch_episodes_subtitles_serialize(
        self,
        seriesid,
        episodeid,
        language,
        forced,
        hi,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if seriesid is not None:
            
            _query_params.append(('seriesid', seriesid))
            
        if episodeid is not None:
            
            _query_params.append(('episodeid', episodeid))
            
        if language is not None:
            
            _query_params.append(('language', language))
            
        if forced is not None:
            
            _query_params.append(('forced', forced))
            
        if hi is not None:
            
            _query_params.append(('hi', hi))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter




        # authentication setting
        _auth_settings: List[str] = [
            'apikey'
        ]

        return self.api_client.param_serialize(
            method='PATCH',
            resource_path='/episodes/subtitles',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def post_episodes_subtitles(
        self,
        seriesid: Annotated[StrictInt, Field(description="Series ID")],
        episodeid: Annotated[StrictInt, Field(description="Episode ID")],
        language: Annotated[StrictStr, Field(description="Language code2")],
        forced: Annotated[StrictStr, Field(description="Forced true/false as string")],
        hi: Annotated[StrictStr, Field(description="HI true/false as string")],
        file: Annotated[Union[StrictBytes, StrictStr, Tuple[StrictStr, StrictBytes]], Field(description="Subtitles file as file upload object")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> None:
        """Upload an episode subtitles


        :param seriesid: Series ID (required)
        :type seriesid: int
        :param episodeid: Episode ID (required)
        :type episodeid: int
        :param language: Language code2 (required)
        :type language: str
        :param forced: Forced true/false as string (required)
        :type forced: str
        :param hi: HI true/false as string (required)
        :type hi: str
        :param file: Subtitles file as file upload object (required)
        :type file: bytearray
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._post_episodes_subtitles_serialize(
            seriesid=seriesid,
            episodeid=episodeid,
            language=language,
            forced=forced,
            hi=hi,
            file=file,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '500': None,
            '409': None,
            '404': None,
            '401': None,
            '204': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def post_episodes_subtitles_with_http_info(
        self,
        seriesid: Annotated[StrictInt, Field(description="Series ID")],
        episodeid: Annotated[StrictInt, Field(description="Episode ID")],
        language: Annotated[StrictStr, Field(description="Language code2")],
        forced: Annotated[StrictStr, Field(description="Forced true/false as string")],
        hi: Annotated[StrictStr, Field(description="HI true/false as string")],
        file: Annotated[Union[StrictBytes, StrictStr, Tuple[StrictStr, StrictBytes]], Field(description="Subtitles file as file upload object")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[None]:
        """Upload an episode subtitles


        :param seriesid: Series ID (required)
        :type seriesid: int
        :param episodeid: Episode ID (required)
        :type episodeid: int
        :param language: Language code2 (required)
        :type language: str
        :param forced: Forced true/false as string (required)
        :type forced: str
        :param hi: HI true/false as string (required)
        :type hi: str
        :param file: Subtitles file as file upload object (required)
        :type file: bytearray
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._post_episodes_subtitles_serialize(
            seriesid=seriesid,
            episodeid=episodeid,
            language=language,
            forced=forced,
            hi=hi,
            file=file,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '500': None,
            '409': None,
            '404': None,
            '401': None,
            '204': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def post_episodes_subtitles_without_preload_content(
        self,
        seriesid: Annotated[StrictInt, Field(description="Series ID")],
        episodeid: Annotated[StrictInt, Field(description="Episode ID")],
        language: Annotated[StrictStr, Field(description="Language code2")],
        forced: Annotated[StrictStr, Field(description="Forced true/false as string")],
        hi: Annotated[StrictStr, Field(description="HI true/false as string")],
        file: Annotated[Union[StrictBytes, StrictStr, Tuple[StrictStr, StrictBytes]], Field(description="Subtitles file as file upload object")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Upload an episode subtitles


        :param seriesid: Series ID (required)
        :type seriesid: int
        :param episodeid: Episode ID (required)
        :type episodeid: int
        :param language: Language code2 (required)
        :type language: str
        :param forced: Forced true/false as string (required)
        :type forced: str
        :param hi: HI true/false as string (required)
        :type hi: str
        :param file: Subtitles file as file upload object (required)
        :type file: bytearray
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._post_episodes_subtitles_serialize(
            seriesid=seriesid,
            episodeid=episodeid,
            language=language,
            forced=forced,
            hi=hi,
            file=file,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '500': None,
            '409': None,
            '404': None,
            '401': None,
            '204': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _post_episodes_subtitles_serialize(
        self,
        seriesid,
        episodeid,
        language,
        forced,
        hi,
        file,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if seriesid is not None:
            
            _query_params.append(('seriesid', seriesid))
            
        if episodeid is not None:
            
            _query_params.append(('episodeid', episodeid))
            
        if language is not None:
            
            _query_params.append(('language', language))
            
        if forced is not None:
            
            _query_params.append(('forced', forced))
            
        if hi is not None:
            
            _query_params.append(('hi', hi))
            
        # process the header parameters
        # process the form parameters
        if file is not None:
            _files['file'] = file
        # process the body parameter



        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'multipart/form-data'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'apikey'
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/episodes/subtitles',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


