# coding: utf-8

"""
    Bazarr

    API docs for Bazarr

    The version of the OpenAPI document: 1.5.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictInt, StrictStr
from typing import Optional
from typing_extensions import Annotated

from bazarr.api_client import ApiClient, RequestSerialized
from bazarr.api_response import ApiResponse
from bazarr.rest import RESTResponseType


class SubtitlesApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def get_subtitles(
        self,
        subtitles_path: Annotated[StrictStr, Field(description="External subtitles file path")],
        sonarr_episode_id: Annotated[Optional[StrictInt], Field(description="Sonarr Episode ID")] = None,
        radarr_movie_id: Annotated[Optional[StrictInt], Field(description="Radarr Movie ID")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> None:
        """Return available audio and embedded subtitles tracks with external subtitles

        Used for manual subsync modal

        :param subtitles_path: External subtitles file path (required)
        :type subtitles_path: str
        :param sonarr_episode_id: Sonarr Episode ID
        :type sonarr_episode_id: int
        :param radarr_movie_id: Radarr Movie ID
        :type radarr_movie_id: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_subtitles_serialize(
            subtitles_path=subtitles_path,
            sonarr_episode_id=sonarr_episode_id,
            radarr_movie_id=radarr_movie_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '401': None,
            '200': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_subtitles_with_http_info(
        self,
        subtitles_path: Annotated[StrictStr, Field(description="External subtitles file path")],
        sonarr_episode_id: Annotated[Optional[StrictInt], Field(description="Sonarr Episode ID")] = None,
        radarr_movie_id: Annotated[Optional[StrictInt], Field(description="Radarr Movie ID")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[None]:
        """Return available audio and embedded subtitles tracks with external subtitles

        Used for manual subsync modal

        :param subtitles_path: External subtitles file path (required)
        :type subtitles_path: str
        :param sonarr_episode_id: Sonarr Episode ID
        :type sonarr_episode_id: int
        :param radarr_movie_id: Radarr Movie ID
        :type radarr_movie_id: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_subtitles_serialize(
            subtitles_path=subtitles_path,
            sonarr_episode_id=sonarr_episode_id,
            radarr_movie_id=radarr_movie_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '401': None,
            '200': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_subtitles_without_preload_content(
        self,
        subtitles_path: Annotated[StrictStr, Field(description="External subtitles file path")],
        sonarr_episode_id: Annotated[Optional[StrictInt], Field(description="Sonarr Episode ID")] = None,
        radarr_movie_id: Annotated[Optional[StrictInt], Field(description="Radarr Movie ID")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Return available audio and embedded subtitles tracks with external subtitles

        Used for manual subsync modal

        :param subtitles_path: External subtitles file path (required)
        :type subtitles_path: str
        :param sonarr_episode_id: Sonarr Episode ID
        :type sonarr_episode_id: int
        :param radarr_movie_id: Radarr Movie ID
        :type radarr_movie_id: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_subtitles_serialize(
            subtitles_path=subtitles_path,
            sonarr_episode_id=sonarr_episode_id,
            radarr_movie_id=radarr_movie_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '401': None,
            '200': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_subtitles_serialize(
        self,
        subtitles_path,
        sonarr_episode_id,
        radarr_movie_id,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if subtitles_path is not None:
            
            _query_params.append(('subtitlesPath', subtitles_path))
            
        if sonarr_episode_id is not None:
            
            _query_params.append(('sonarrEpisodeId', sonarr_episode_id))
            
        if radarr_movie_id is not None:
            
            _query_params.append(('radarrMovieId', radarr_movie_id))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter




        # authentication setting
        _auth_settings: List[str] = [
            'apikey'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/subtitles',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def patch_subtitles(
        self,
        action: Annotated[StrictStr, Field(description="Action from [\"sync\", \"translate\" or mods name]")],
        language: Annotated[StrictStr, Field(description="Language code2")],
        path: Annotated[StrictStr, Field(description="Subtitles file path")],
        type: Annotated[StrictStr, Field(description="Media type from [\"episode\", \"movie\"]")],
        id: Annotated[StrictInt, Field(description="Media ID (episodeId, radarrId)")],
        forced: Annotated[Optional[StrictStr], Field(description="Forced subtitles from [\"True\", \"False\"]")] = None,
        hi: Annotated[Optional[StrictStr], Field(description="HI subtitles from [\"True\", \"False\"]")] = None,
        original_format: Annotated[Optional[StrictStr], Field(description="Use original subtitles format from [\"True\", \"False\"]")] = None,
        reference: Annotated[Optional[StrictStr], Field(description="Reference to use for sync from video file track number (a:0) or some subtitles file path")] = None,
        max_offset_seconds: Annotated[Optional[StrictStr], Field(description="Maximum offset seconds to allow")] = None,
        no_fix_framerate: Annotated[Optional[StrictStr], Field(description="Don't try to fix framerate from [\"True\", \"False\"]")] = None,
        gss: Annotated[Optional[StrictStr], Field(description="Use Golden-Section Search from [\"True\", \"False\"]")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> None:
        """Apply mods/tools on external subtitles


        :param action: Action from [\"sync\", \"translate\" or mods name] (required)
        :type action: str
        :param language: Language code2 (required)
        :type language: str
        :param path: Subtitles file path (required)
        :type path: str
        :param type: Media type from [\"episode\", \"movie\"] (required)
        :type type: str
        :param id: Media ID (episodeId, radarrId) (required)
        :type id: int
        :param forced: Forced subtitles from [\"True\", \"False\"]
        :type forced: str
        :param hi: HI subtitles from [\"True\", \"False\"]
        :type hi: str
        :param original_format: Use original subtitles format from [\"True\", \"False\"]
        :type original_format: str
        :param reference: Reference to use for sync from video file track number (a:0) or some subtitles file path
        :type reference: str
        :param max_offset_seconds: Maximum offset seconds to allow
        :type max_offset_seconds: str
        :param no_fix_framerate: Don't try to fix framerate from [\"True\", \"False\"]
        :type no_fix_framerate: str
        :param gss: Use Golden-Section Search from [\"True\", \"False\"]
        :type gss: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._patch_subtitles_serialize(
            action=action,
            language=language,
            path=path,
            type=type,
            id=id,
            forced=forced,
            hi=hi,
            original_format=original_format,
            reference=reference,
            max_offset_seconds=max_offset_seconds,
            no_fix_framerate=no_fix_framerate,
            gss=gss,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '500': None,
            '409': None,
            '404': None,
            '401': None,
            '204': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def patch_subtitles_with_http_info(
        self,
        action: Annotated[StrictStr, Field(description="Action from [\"sync\", \"translate\" or mods name]")],
        language: Annotated[StrictStr, Field(description="Language code2")],
        path: Annotated[StrictStr, Field(description="Subtitles file path")],
        type: Annotated[StrictStr, Field(description="Media type from [\"episode\", \"movie\"]")],
        id: Annotated[StrictInt, Field(description="Media ID (episodeId, radarrId)")],
        forced: Annotated[Optional[StrictStr], Field(description="Forced subtitles from [\"True\", \"False\"]")] = None,
        hi: Annotated[Optional[StrictStr], Field(description="HI subtitles from [\"True\", \"False\"]")] = None,
        original_format: Annotated[Optional[StrictStr], Field(description="Use original subtitles format from [\"True\", \"False\"]")] = None,
        reference: Annotated[Optional[StrictStr], Field(description="Reference to use for sync from video file track number (a:0) or some subtitles file path")] = None,
        max_offset_seconds: Annotated[Optional[StrictStr], Field(description="Maximum offset seconds to allow")] = None,
        no_fix_framerate: Annotated[Optional[StrictStr], Field(description="Don't try to fix framerate from [\"True\", \"False\"]")] = None,
        gss: Annotated[Optional[StrictStr], Field(description="Use Golden-Section Search from [\"True\", \"False\"]")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[None]:
        """Apply mods/tools on external subtitles


        :param action: Action from [\"sync\", \"translate\" or mods name] (required)
        :type action: str
        :param language: Language code2 (required)
        :type language: str
        :param path: Subtitles file path (required)
        :type path: str
        :param type: Media type from [\"episode\", \"movie\"] (required)
        :type type: str
        :param id: Media ID (episodeId, radarrId) (required)
        :type id: int
        :param forced: Forced subtitles from [\"True\", \"False\"]
        :type forced: str
        :param hi: HI subtitles from [\"True\", \"False\"]
        :type hi: str
        :param original_format: Use original subtitles format from [\"True\", \"False\"]
        :type original_format: str
        :param reference: Reference to use for sync from video file track number (a:0) or some subtitles file path
        :type reference: str
        :param max_offset_seconds: Maximum offset seconds to allow
        :type max_offset_seconds: str
        :param no_fix_framerate: Don't try to fix framerate from [\"True\", \"False\"]
        :type no_fix_framerate: str
        :param gss: Use Golden-Section Search from [\"True\", \"False\"]
        :type gss: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._patch_subtitles_serialize(
            action=action,
            language=language,
            path=path,
            type=type,
            id=id,
            forced=forced,
            hi=hi,
            original_format=original_format,
            reference=reference,
            max_offset_seconds=max_offset_seconds,
            no_fix_framerate=no_fix_framerate,
            gss=gss,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '500': None,
            '409': None,
            '404': None,
            '401': None,
            '204': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def patch_subtitles_without_preload_content(
        self,
        action: Annotated[StrictStr, Field(description="Action from [\"sync\", \"translate\" or mods name]")],
        language: Annotated[StrictStr, Field(description="Language code2")],
        path: Annotated[StrictStr, Field(description="Subtitles file path")],
        type: Annotated[StrictStr, Field(description="Media type from [\"episode\", \"movie\"]")],
        id: Annotated[StrictInt, Field(description="Media ID (episodeId, radarrId)")],
        forced: Annotated[Optional[StrictStr], Field(description="Forced subtitles from [\"True\", \"False\"]")] = None,
        hi: Annotated[Optional[StrictStr], Field(description="HI subtitles from [\"True\", \"False\"]")] = None,
        original_format: Annotated[Optional[StrictStr], Field(description="Use original subtitles format from [\"True\", \"False\"]")] = None,
        reference: Annotated[Optional[StrictStr], Field(description="Reference to use for sync from video file track number (a:0) or some subtitles file path")] = None,
        max_offset_seconds: Annotated[Optional[StrictStr], Field(description="Maximum offset seconds to allow")] = None,
        no_fix_framerate: Annotated[Optional[StrictStr], Field(description="Don't try to fix framerate from [\"True\", \"False\"]")] = None,
        gss: Annotated[Optional[StrictStr], Field(description="Use Golden-Section Search from [\"True\", \"False\"]")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Apply mods/tools on external subtitles


        :param action: Action from [\"sync\", \"translate\" or mods name] (required)
        :type action: str
        :param language: Language code2 (required)
        :type language: str
        :param path: Subtitles file path (required)
        :type path: str
        :param type: Media type from [\"episode\", \"movie\"] (required)
        :type type: str
        :param id: Media ID (episodeId, radarrId) (required)
        :type id: int
        :param forced: Forced subtitles from [\"True\", \"False\"]
        :type forced: str
        :param hi: HI subtitles from [\"True\", \"False\"]
        :type hi: str
        :param original_format: Use original subtitles format from [\"True\", \"False\"]
        :type original_format: str
        :param reference: Reference to use for sync from video file track number (a:0) or some subtitles file path
        :type reference: str
        :param max_offset_seconds: Maximum offset seconds to allow
        :type max_offset_seconds: str
        :param no_fix_framerate: Don't try to fix framerate from [\"True\", \"False\"]
        :type no_fix_framerate: str
        :param gss: Use Golden-Section Search from [\"True\", \"False\"]
        :type gss: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._patch_subtitles_serialize(
            action=action,
            language=language,
            path=path,
            type=type,
            id=id,
            forced=forced,
            hi=hi,
            original_format=original_format,
            reference=reference,
            max_offset_seconds=max_offset_seconds,
            no_fix_framerate=no_fix_framerate,
            gss=gss,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '500': None,
            '409': None,
            '404': None,
            '401': None,
            '204': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _patch_subtitles_serialize(
        self,
        action,
        language,
        path,
        type,
        id,
        forced,
        hi,
        original_format,
        reference,
        max_offset_seconds,
        no_fix_framerate,
        gss,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if action is not None:
            
            _query_params.append(('action', action))
            
        if language is not None:
            
            _query_params.append(('language', language))
            
        if path is not None:
            
            _query_params.append(('path', path))
            
        if type is not None:
            
            _query_params.append(('type', type))
            
        if id is not None:
            
            _query_params.append(('id', id))
            
        if forced is not None:
            
            _query_params.append(('forced', forced))
            
        if hi is not None:
            
            _query_params.append(('hi', hi))
            
        if original_format is not None:
            
            _query_params.append(('original_format', original_format))
            
        if reference is not None:
            
            _query_params.append(('reference', reference))
            
        if max_offset_seconds is not None:
            
            _query_params.append(('max_offset_seconds', max_offset_seconds))
            
        if no_fix_framerate is not None:
            
            _query_params.append(('no_fix_framerate', no_fix_framerate))
            
        if gss is not None:
            
            _query_params.append(('gss', gss))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter




        # authentication setting
        _auth_settings: List[str] = [
            'apikey'
        ]

        return self.api_client.param_serialize(
            method='PATCH',
            resource_path='/subtitles',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


